### ISSUE TITLE
service-manager always starts openshift

### ISSUE THREAD

**Issue by optak** [projectatomic/vagrant-service-manager#162]
It looks that service-manager is responsible for (re)starting openshift.service always, even with Vagrantfile which should start k8s services instead of openshift.
There is call for switch to openshift during vagrant up:
`INFO ssh: Execute:  sccli openshift (sudo=true)`

**Comment by optak** [comment]
With vagrant-service-manager-0.0.5 I don't have this issue, so it is bug in vagrnt-service-manager.

**Comment by navidshaikh** [comment]
For CDK box, the default setup is to start the `openshift` service. For `kubernetes` [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile#L38) in ADB repo, `kubernetes` is configured using shell provisioning, which VSM plugin do not have control over.

Ideally, VSM should have understood if the a particular service is configured via shell provisioning, however IMO its not feasible to parse the pattern in shell provisioning block and guess that. The fix should be to have a single way to configure the services in the box. ATM, VSM can configure docker and openshift service in the box with line
`config.servicemanager.services = 'docker, openshift'`
and it does not have support to configure `kubernetes` services, thus one has to explicitly configure the kubernetes services via shell provisioning.

ATM, possible workaround is to add following line in the kubernetes [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile#L38) 

```
`config.servicemanager.services = 'docker'`
```

This is a fix for CDK box, since openshift and docker were default configured services for CDK, and here we are asking _explicitly_ to configure only docker, VSM will not start the openshift service and respective block in shell provisioning will have its effect.

**Comment by LalatenduMohanty** [comment]
Corresponding issue https://github.com/projectatomic/adb-atomic-developer-bundle/issues/334

This is fixed with https://github.com/projectatomic/adb-atomic-developer-bundle/pull/335
