### ISSUE TITLE
Put Gemfile.lock under version control

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#203]
Adding the lock file will make the setup repeatable.

**Comment by brgnepal** [comment]
It is not recommended to check-in `Gemfile.lock` while building gem. 
Check here http://stackoverflow.com/a/4151540/1120530

**Comment by hferentschik** [comment]
> It is not recommended to check-in Gemfile.lock while building gem. 

That depends. In our case we are locking down the development dependencies which makes sense imo. Also depending on your work flow having Gemfile.lock _not_ in the repository won't help you to detect any compatibility issues (you would have to regularly delete the lock file).

**Comment by brgnepal** [comment]
As per reference of this answer http://stackoverflow.com/a/7919948/1120530.

> No, the Gemfile.lock file is an aid for deployment, not for development.
> It is used to recreate an exact replica of your environment on another systems, something that is not (usually) required for development.

IMO, check-in `Gemfile.lock` has pros and cons.
_Pros_ : It would help in development but agree with above shared link that `Gemfile.lock` are an aid for deployment. 
_Cons_: We may not know whether future version of the dependent gems will work or not since we almost freezed the gems version. Also, we may not be participating in respective upstream dependent gems development by allowing `Gemfile.lock`.

Adding [this blog article](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) by Yahuda Katz in support of not adding `Gemfile.lock`.
Highlights at the bottom of the article.

```
This is also why we recommend that people do not check in their Gemfile.lock 
files in gem development. That file is emitted by bundler, and guarantees that 
all gems, including dependencies of dependencies, remain the same. However, when
doing gem development, you want to know immediately when some change in the 
overall ecosystem breaks your setup. While you may want to insist on using a 
particular gem from its git location, you do not want to hardcode your development
to a very specific set of gems, only to find out later that a gem released after 
you ran bundle install, but compatible with your version range, doesn't work 
with your code.

It's not a way to guarantee that your code works on all versions that you 
specified in your .gemspec, but the incentive to lock down the exact versions of
each gem simply doesn't exist when the users of your code will get it 
via gem install.
```

**Comment by hferentschik** [comment]
Closing this one. If we go down the path having conditionals in the _Gemfile_ it does not make sense anymore to check in the lock file.
