### ISSUE TITLE
Remove 1.3.0.dev version in version.rb file

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#339]
I found `1.3.0.dev` in [version file](https://github.com/projectatomic/vagrant-service-manager/blob/master/lib/vagrant-service-manager/version.rb).

Is it by mistake?
If not then are we following any new policy to update version here? If yes then we need to discuss first.

**Comment by LalatenduMohanty** [comment]
I was not aware of the change but I think 1.3.0.dev makes sense as if some one builds from master branch then the gem version should be different than the released one.

**Comment by brgnepal** [comment]
If we want such feature then I believe it make sense to go through discussion and add proper docs.

**Comment by LalatenduMohanty** [comment]
@budhrg sure. But it is a kind of standard practice in many upstream projects. Having a dev version also helps to guess what would be the next released version. So +1 from me for `1.3.0.dev`.

**Comment by hferentschik** [comment]
This was intentionally. I will document this in an upcoming pull request. This is common practice to increment the version after a release. This helps when then testing new gems, since by keeping the old gem version one never knows whether one tests the last stable release of the dev version. The version is not set in stone, obviously know it will become 1.2.1 as a next release. However after the release we will again switch back to the envisioned next release of 1.3.0.dev.
