### ISSUE TITLE
Update gemspec with development dependencies

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#341]
Updating gemspec with development dependencies will reflect the changes in rubygem's gem page.
This will help to quickly know the dependencies through rubygems instead of going through github repo and check Gemfile or gemspec.

Refer this nice blog post on [`roles of Gemfile and .gemspec` 2nd para](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)

Example gem:
![screenshot from 2016-07-15 13-48-20](https://cloud.githubusercontent.com/assets/1132451/16868015/e222f9be-4a92-11e6-8f30-5a6bdf922af3.png)

**Comment by hferentschik** [comment]
I am torn on this one, since we are not able to move all development dependencies. the Vagrant, vagrant-libvirt and fog-libvirt will always have to stay in the Gemfile. I find that unfortunate. Also, we will always have to keep the plugin group. 

We could combine the _devlopment_ and _test_ group in the _Gemfile_ though.

In the end as user of a Gemfile I am not really interested in development dependencies.

**Comment by brgnepal** [comment]
Closing this no consensus in putting dependencies in `.gemspec` file.
