### ISSUE TITLE
Check for correct TLS certs pair

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#80]
User story:
I am an ADB user, I `vagrant up` my box and using `vagrant-service-manager` plugin I copied the client side certs in my host directory. I `vagrant destroy` after completing my work (the copied over certs stays un-touched). The next day I `vagrant up` again (which will re-generate the certs inside the box), I try to copy the certs using `vagrant-service-manager`, however the certs will not be copied over since yesterday's certs are already there, and plugin will not copy, but just show the configuration info.

Problem:
Now there are incorrect client side certs on host. 

Solution:
plugin should ensure that the client side certs are correct and are part of the pair from the server side certs.

How does this work today:
`rm -rf .vagrant/machines/default/virtualbox/docker` manually before copying the certs using plugin to ensure I have correct client side certs.

**Comment by brgnepal** [comment]
Can we do like this?
If there is folder `.vagrant/machines/default/virtualbox/docker` exists then remove it and then perform normal operation.

**Comment by LalatenduMohanty** [comment]
It should be done again through `Vagrant destroy` using hook.  `Vagrant destroy` should delete the certs IMO.

**Comment by brgnepal** [comment]
+1 for `vagrant destroy` approach.

**Comment by navidshaikh** [comment]
The certs pair in guest and host be invalid if we docker daemon is restarted, IMO the check should compare the client side certs in the guest with certs on host to decide if copy is needed.

**Comment by mmalina** [comment]
Hi, from the issue description it seems that this is reproducible only if you use vagrant destroy and then vagrant up. But for me this happens even if I just use vagrant halt and then vagrant up.
Maybe that's what @navidshaikh says in his last comment - that merely restarting docker daemon will do this.
This is what reproduces the problem for me:
vagrant destroy #to make sure you start from scratch
vagrant up
eval "$(vagrant service-manager env docker)"
docker ps #works fine
vagrant halt
vagrant up
eval "$(vagrant service-manager env docker)"
docker ps #FAIL 
An error occurred trying to connect: Get https://10.1.2.2:2376/v1.20/containers/json: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "example.com")

I'm using rhel-cdk-kubernetes-7.2-21.x86_64.vagrant-virtualbox.box and the latest cdk build (I believe it's Beta5) with service manager 0.0.4

**Comment by brgnepal** [comment]
@mmalina This fix is not released yet. Could you download [this gem](https://www.dropbox.com/s/ihkcrqszzuqjhtc/vagrant-service-manager-0.0.4.1.gem) which contains this fix and check again? 
Please note that I have changed the version to `0.0.4.1` for show the changes.

**Comment by mmalina** [comment]
@budhrg thanks. I tried again with the 0.0.4.1 gem and now it works correctly for my use case!
This is what I did:
11701  vagrant halt
11702  vagrant up
11703  eval "$(vagrant service-manager env docker)"
11704  docker ps **#this still failed for me**
11705  vagrant halt
11706  vagrant plugin install ~/Downloads/vagrant-service-manager-0.0.4.1.gem 
11707  vagrant up
11708  eval "$(vagrant service-manager env docker)"
11709  docker ps **#now it worked fine**

**Comment by brgnepal** [comment]
@mmalina Thanks for verifying it. :+1:

**Comment by hferentschik** [comment]
> It should be done again through Vagrant destroy using hook. Vagrant destroy should delete the certs IMO.

+1, that's probably a good idea, but it should go hand in hand with copying the certs when they are actually generated - https://github.com/projectatomic/vagrant-service-manager/issues/122

See also - https://issues.jboss.org/browse/JBIDE-21845

Also, why not write down a bunch of acceptance tests which clearly outline/show what the expectations are around the certs in relation to the Vagrant life cycle. We really chase our tail on this one :-(

**Comment by hferentschik** [comment]
Why is this release (0.0.4.1) not on rubygems.org? Also, do we really want to add yet another level to the version string. What would be the purpose of that? Three levels should be sufficient and support a scheme like MAJOR.MINOR.PATCH aligned with semantic versioning.

For that reason I'd suggest to do a 0.0.5 release now which also gets pushed to rubygems.org. Then prior to GA of ADB/CDK we should go 1.0.0 and start applying semantic versioning with the releases.

**Comment by brgnepal** [comment]
@hferentschik That's just added to differentiate it with older version `(0.0.4)`. 
Here, we are not adding yet another level. I have just created a gem which includes this fix and given to Martin to testing since he was probably using the version which didn't have fix.

**Comment by hferentschik** [comment]
> Here, we are not adding yet another level. I have just created a gem which includes this fix and given to Martin to testing since he was probably using the version which didn't have fix.

There are many people relying on this plugin and I hear from various people that they have problems with out of sync certificates. This is a high priority issue. If you have a fix, release it, so that we can all benefit from it. It really does not hurt to create a 0.0.5, right? And it should not take to much time either.
