### ISSUE TITLE
TLS certificates are not valid for private network IP

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#95]
Tested with service-manager 0.0.3 and latest CDK build

```
$ vagrant up
$ eval "$(vagrant service-manager env docker)"
$ docker ps 
An error occurred trying to connect: Get https://10.1.2.2:2376/v1.20/containers/json: x509: certificate is valid for 10.0.2.15, not 10.1.2.2
```

This is a regression. We had this issue before. The certificate must allow connections via the private network IP.

Downgrading to service-manager 0.0.2 is a work around, since there it still works.

**Comment by hferentschik** [comment]
This is blocker. If possible we should try to get a 0.0.4 out asap (not sure whether the ADB/CDK needs changes as well!?)

**Comment by navidshaikh** [comment]
@hferentschik : Can you please paste the Vagrantfile to reproduce the issue?

**Comment by navidshaikh** [comment]
or may be you have used the same working directory for box(es) with different private networking IPs set?

(given the same working directory) For box A, if you have configured the private network -> vagrant up -> vagrant service-manager env docker, destroyed the box (but the client side certs are still on host), re-configure Vagrantfile --> vagrant up --> vagrant service-manager env docker (no certs are copied over since plugin sees the client side certs on host) --> BUG! (https://github.com/projectatomic/vagrant-service-manager/issues/80)

is this the case?

**Comment by hferentschik** [comment]
You can use the Vagrantfile from openshift-vagrant and I always started from clean directories making sure all state is deleted. In particular I deleted the _.vagrant_ directory which contains the certs.

Also by switching between 0.0.2 and 0.0.3 of the plugin I can make the issue appear and disappear.

**Comment by navidshaikh** [comment]
I tried re-producing this issue. The issue is re-producible only with CDK box but not for ADB box.

**Comment by LalatenduMohanty** [comment]
@navidshaikh and the PRs are mostly tested against ADB :(

**Comment by navidshaikh** [comment]
@LalatenduMohanty : Correct, we a need CI job for supported boxes.

**Comment by brgnepal** [comment]
+1 for CI job for supported boxes

**Comment by navidshaikh** [comment]
The issue is, the config + hook approach to re-configure (restart) docker daemon as part of `vagrant up` is not able to detect cdk as a supported box and thus not executing any code (restarting docker daemon) when user brings up the box (vagrant box). This is causing the docker daemon configuration and TLS certs to be generated with NAT interface and private networking attached later on to the box.

**Comment by hferentschik** [comment]
>  +1 for CI job for supported boxes

+100 including some smoke tests maybe? In openshift-vagrant we have a few serverspec tests which are imo easy to write and hopefully execute. From the developer tooling side the plan is definitely to extend on these tests. In a perfect world these tests would already run as part of these CI jobs.

**Comment by dkutalek** [comment]
We are now in the process of choosing a testing framework which fits best.
Of course, bugs should be covered with automated tests in CI 
and we are working on that goal.

**Comment by hferentschik** [comment]
In relation to the service-manager, I would envision that you just need to test Vagrant setups. One against ADB and one against CDK. Then you run a bunch of rspec tests against either setup to verify that the view commands we have work.

**Comment by hferentschik** [comment]
Btw, the tests should be runnable from the code base by the developer. That is even more important than something CI. You want to be able to change and add add code w/o breaking existing code. Having to check in code and then wait for a CI result would be taking too long.

**Comment by dkutalek** [comment]
Works for me on Mac, with version 0.0.4 when trying directly after the first vagrant up of the box.

Used docker 1.7.1 client installed with:
brew install homebrew/versions/docker171

(there is only 1.7.1 and 1.9.1 in brew.sh, not 1.8.x one)
